'use client';

import { useEffect, useMemo, useState } from 'react';

const empty = { name:'', url:'', logo:'', countryCode:'OTHER', countryLabel:'Other', categoryKey:'other', categoryLabel:'Other', language:'', enabled:true, featured:false, home:true, customSection:'', sortOrder:0 };

export default function AdminPage() {
  const [secret,setSecret]=useState(''); const [authed,setAuthed]=useState(false); const [channels,setChannels]=useState([]); const [settings,setSettings]=useState({}); const [form,setForm]=useState(empty); const [editing,setEditing]=useState(null); const [search,setSearch]=useState(''); const [tab,setTab]=useState('channels'); const [m3u,setM3u]=useState(''); const [imported,setImported]=useState([]); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false);

  async function api(url, options={}) { const res=await fetch(url,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}}); const data=await res.json().catch(()=>({})); if(!res.ok) throw new Error(data.error||`HTTP ${res.status}`); return data; }
  async function login(e){e.preventDefault();setBusy(true);setMsg('');try{await api('/api/admin/auth',{method:'POST',body:JSON.stringify({secret})});setAuthed(true);await load();}catch(e){setMsg(e.message)}finally{setBusy(false)}}
  async function load(){const [c,s]=await Promise.all([api('/api/admin/channels'),api('/api/admin/settings')]);setChannels(c.channels||[]);setSettings(s||{});}
  useEffect(()=>{ if(authed) load().catch(e=>setMsg(e.message)); },[authed]);
  async function saveChannel(e){e.preventDefault();setBusy(true);try{const d=await api('/api/admin/channels',{method:'POST',body:JSON.stringify({channel:{...form,id:editing||undefined}})});setChannels(d.channels);setForm(empty);setEditing(null);setMsg('Channel saved.');}catch(e){setMsg(e.message)}finally{setBusy(false)}}
  async function remove(ids){if(!ids.length||!confirm(`Delete ${ids.length} channel(s)?`))return;setBusy(true);try{const d=await api('/api/admin/channels',{method:'DELETE',body:JSON.stringify({ids})});setChannels(d.channels);setMsg('Channel removed.')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
  async function toggle(c){try{const d=await api('/api/admin/channels',{method:'PUT',body:JSON.stringify({channels:channels.map(x=>x.id===c.id?{...x,enabled:!x.enabled}:x)})});setChannels(d.channels)}catch(e){setMsg(e.message)}}
  async function saveSettings(e){e.preventDefault();setBusy(true);try{const d=await api('/api/admin/settings',{method:'PUT',body:JSON.stringify(settings)});setSettings(d);setMsg('Settings saved.')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
  async function importM3U(){setBusy(true);try{const d=await api('/api/admin/channels',{method:'POST',body:JSON.stringify({action:'import-m3u',url:m3u})});setImported(d.channels||[]);setMsg(`${d.count} channels scanned. Select what you want to add.`)}catch(e){setMsg(e.message)}finally{setBusy(false)}}
  async function addImported(){setBusy(true);try{const selected=imported.filter(x=>x._selected!==false).map((x,i)=>({...x,sortOrder:channels.length+i}));const d=await api('/api/admin/channels',{method:'PUT',body:JSON.stringify({channels:[...channels,...selected]})});setChannels(d.channels);setImported([]);setMsg(`${selected.length} imported.`)}catch(e){setMsg(e.message)}finally{setBusy(false)}}
  const filtered=useMemo(()=>channels.filter(c=>`${c.name} ${c.countryLabel} ${c.categoryLabel}`.toLowerCase().includes(search.toLowerCase())),[channels,search]);

  if(!authed) return <main className="min-h-screen px-4 py-16"><div className="mx-auto max-w-md rounded-2xl border border-nex-border bg-nex-panel p-6 shadow-2xl"><div className="mb-6"><p className="text-xs font-bold uppercase tracking-[.25em] text-nex-red">NexLive Control</p><h1 className="mt-2 text-3xl font-black">Admin Login</h1><p className="mt-2 text-sm text-nex-muted">Use the server-side NEXLIVE_ADMIN_SECRET.</p></div><form onSubmit={login} className="space-y-3"><input type="password" value={secret} onChange={e=>setSecret(e.target.value)} placeholder="Admin secret" className="nex-input" autoComplete="current-password"/><button disabled={busy} className="nex-button w-full">{busy?'Signing in…':'Sign in'}</button></form>{msg&&<p className="mt-4 text-sm text-nex-red">{msg}</p>}</div></main>;

  return <main className="min-h-screen px-4 py-6"><div className="mx-auto max-w-7xl">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-nex-red">NexLive Control</p><h1 className="mt-1 text-3xl font-black">Admin CMS</h1><p className="text-sm text-nex-muted">Manage channels, imports and player branding without touching the code.</p></div><button className="nex-button-secondary" onClick={async()=>{await fetch('/api/admin/auth',{method:'DELETE'});setAuthed(false)}}>Log out</button></div>
    {msg&&<div className="my-4 rounded-xl border border-nex-border bg-nex-panel px-4 py-3 text-sm">{msg}</div>}
    <div className="mt-5 flex gap-2 overflow-x-auto"><button onClick={()=>setTab('channels')} className={tab==='channels'?'nex-tab active':'nex-tab'}>Channels</button><button onClick={()=>setTab('import')} className={tab==='import'?'nex-tab active':'nex-tab'}>Import M3U</button><button onClick={()=>setTab('settings')} className={tab==='settings'?'nex-tab active':'nex-tab'}>Branding</button></div>

    {tab==='channels'&&<section className="mt-5 grid gap-5 lg:grid-cols-[360px_1fr]"><form onSubmit={saveChannel} className="nex-panel p-5 h-fit space-y-3"><h2 className="text-lg font-bold">{editing?'Edit channel':'Add channel'}</h2>{['name','url','logo','countryCode','countryLabel','categoryKey','categoryLabel','language','customSection'].map(k=><input key={k} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})} placeholder={k} className="nex-input" required={k==='name'||k==='url'}/>)}<div className="grid grid-cols-3 gap-2 text-xs"><label><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/> Enabled</label><label><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Featured</label><label><input type="checkbox" checked={form.home} onChange={e=>setForm({...form,home:e.target.checked})}/> Home</label></div><div className="flex gap-2"><button disabled={busy} className="nex-button flex-1">{editing?'Update':'Add'}</button>{editing&&<button type="button" className="nex-button-secondary" onClick={()=>{setEditing(null);setForm(empty)}}>Cancel</button>}</div></form>
      <div className="nex-panel overflow-hidden"><div className="flex flex-col gap-3 border-b border-nex-border p-4 sm:flex-row"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search channels…" className="nex-input flex-1"/><button className="nex-button-secondary" onClick={()=>remove(filtered.map(c=>c.id))}>Delete filtered</button></div><div className="max-h-[70vh] overflow-auto">{filtered.map(c=><div key={c.id} className="flex items-center gap-3 border-b border-nex-border px-4 py-3"><div className="h-10 w-14 shrink-0 rounded bg-nex-panel2 p-1">{c.logo&&<img src={c.logo} className="h-full w-full object-contain" alt=""/>}</div><div className="min-w-0 flex-1"><p className="truncate font-semibold">{c.name}</p><p className="truncate text-xs text-nex-muted">{c.countryLabel} · {c.categoryLabel}</p></div><button onClick={()=>toggle(c)} className="text-xs">{c.enabled?'ON':'OFF'}</button><button onClick={()=>{setEditing(c.id);setForm(c);window.scrollTo({top:0,behavior:'smooth'})}} className="nex-link">Edit</button><button onClick={()=>remove([c.id])} className="text-xs text-nex-red">Delete</button></div>)}{filtered.length===0&&<p className="p-10 text-center text-sm text-nex-muted">No channels.</p>}</div></div></section>}

    {tab==='import'&&<section className="mt-5 nex-panel p-5"><h2 className="text-xl font-bold">Import M3U</h2><p className="mt-1 text-sm text-nex-muted">Paste a public M3U playlist URL. The server scans it; streams are still played directly by the browser.</p><div className="mt-4 flex flex-col gap-2 sm:flex-row"><input value={m3u} onChange={e=>setM3u(e.target.value)} placeholder="https://example.com/playlist.m3u" className="nex-input flex-1"/><button disabled={busy} onClick={importM3U} className="nex-button">Scan playlist</button></div>{imported.length>0&&<><div className="mt-5 flex items-center justify-between"><p className="font-semibold">Preview: {imported.length}</p><button className="nex-button" onClick={addImported}>Add selected</button></div><div className="mt-3 max-h-[55vh] overflow-auto rounded-xl border border-nex-border">{imported.map((c,i)=><label key={`${c.id}-${i}`} className="flex items-center gap-3 border-b border-nex-border p-3"><input type="checkbox" checked={c._selected!==false} onChange={e=>setImported(imported.map((x,j)=>j===i?{...x,_selected:e.target.checked}:x))}/><div className="min-w-0"><p className="truncate text-sm font-semibold">{c.name}</p><p className="truncate text-xs text-nex-muted">{c.countryLabel} · {c.categoryLabel}</p></div></label>)}</div></>}</section>}

    {tab==='settings'&&<form onSubmit={saveSettings} className="mt-5 nex-panel p-5"><h2 className="text-xl font-bold">Website & Player Branding</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{['siteName','logoUrl','faviconUrl','description','footer','primaryColor','accentColor','watermarkUrl','watermarkPosition'].map(k=><input key={k} value={settings[k]??''} onChange={e=>setSettings({...settings,[k]:e.target.value})} placeholder={k} className="nex-input"/>)}<label className="nex-check"><input type="checkbox" checked={Boolean(settings.watermarkEnabled)} onChange={e=>setSettings({...settings,watermarkEnabled:e.target.checked})}/> Watermark enabled</label><label className="nex-check">Opacity<input type="number" min="0" max="1" step="0.05" value={settings.watermarkOpacity??.72} onChange={e=>setSettings({...settings,watermarkOpacity:e.target.value})} className="nex-input ml-2 w-28"/></label><label className="nex-check">Size<input type="number" min="16" max="160" value={settings.watermarkSize??42} onChange={e=>setSettings({...settings,watermarkSize:e.target.value})} className="nex-input ml-2 w-28"/></label></div><button disabled={busy} className="nex-button mt-5">Save settings</button></form>}
  </div></main>;
}
